spring:
  application:
    name: palettea-auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
server:
  port: 9000
palettea:
  issuer-uri: ${ISSUER_URI}